Corrige erro de validação para CRDs com múltiplas versões usando tipos complexos (object, array)
lukerops/tf-gapi pull request #13
Opened 2024-02-07 13:29 UTC by daltonmatos

Esse PR remove um dos checks do CRD que na verdade impede que um mesmo CRD tenha múltiplas versões definidas onde essas versões possuem campos complexos (`array` ou `object` ).

Isso acontece pois a saída do um for com `[ ]` é um `tuple`, e quando fazemos `tolist()` dessa tuple a [conversão automática de tipos complexos](https://developer.hashicorp.com/terraform/language/expressions/type-constraints#complex-types) do terraform entra em ação. Especialmente a conversão de tipos dinâmicos, com o uso do `any`. (ref. https://developer.hashicorp.com/terraform/language/expressions/type-constraints#any-with-collection-types).

Nesse caso, quando temos duas versões mas uma delas declara um tipo complexo, isso faz com que um dos elementos da tupla tenha um `type()` diferente dos outros e a conversão para list se torna impossível, segundo as regras do terraform.

Um ponto a favor da remoção desse check é que, segundo a [documentação do terraform](https://developer.hashicorp.com/terraform/language/expressions/type-constraints#complex-type-literals), uma `tuple` e um `list` se comportam de forma igual, ou seja, para efeitos de uso (iterar, acesso via `[<index>]`, etc) poderemos usar o resultado do `for` direto, sem precisar converter para list. 

Um exemplo:

```terraform
locals {
  schemas = [
    {
      specSchema = {
        active = {
          type    = "bool"
          default = "false"
        }
        other = {
          type = "integer"
        }
      }
    },
    {
      specSchema = {
        active = {
          type = "bool"
        }
      }
    },
  ]
}

```
Essa tupla com dois objetos consegue ser convertida para list:

```terraform
> tolist(local.schemas)
tolist([
  {
    "specSchema" = tomap({
      "active" = tomap({
        "default" = "false"
        "type" = "bool"
      })
      "other" = tomap({
        "type" = "array"
      })
    })
  },
  {
    "specSchema" = tomap({
      "active" = tomap({
        "type" = "bool"
      })
    })
  },
])
>  
```

Mas quando transformamos ums dos elementos em um objeto mais complexo, análogo a um dos tipos do CRD, por exemplo, `array`, já não conseguimos mais fazer o `tolist()`.

```terraform
> local.schemas
[
  {
    "specSchema" = {
      "active" = {
        "default" = "false"
        "type" = "bool"
      }
      "other" = {
        "items" = {
          "type" = "string"
        }
        "type" = "array"
      }
    }
  },
  {
    "specSchema" = {
      "active" = {
        "type" = "bool"
      }
    }
  },
]
> tolist(local.schemas)
╷
│ Error: Invalid function argument
│ 
│   on <console-input> line 1:
│   (source code not available)
│ 
│ Invalid value for "v" parameter: cannot convert tuple to list of any single type.
╵
```

2024-02-07 13:30 UTC, daltonmatos commented
@lukerops

2024-03-04 13:01 UTC, lukerops requested changes
Interessante :thinking: não tinha pego um caso que desse erro nisso. Só faz o rebase para a `main` por favor.

2024-03-04 17:33 UTC, daltonmatos commented
Feito.

2024-03-06 19:35 UTC, lukerops approved these changes

2024-03-06 19:37 UTC, merged